### ISSUE TITLE
Some icons not showing up

### ISSUE THREAD

**Issue by robophil** [shripalsoni04/nativescript-material-icons#2]
Hi,
Some icons don't seem to work, while some do. Any reason why this should happen?

```javascript
<label class="mdi-600" [text]="'mdi-hourglass_empty' | fonticon" *ngIf="empty" ></label>
```

**Comment by shripalsoni04** [comment]
I am curious about what are the css rules configured for `mdi-600`. To use any material design icon on an element, you need to set a class which contains css rule `font-family: "Material Icons", "MaterialIcons-Regular"`.

Please check this tutorial http://shripalsoni.com/blog/material-font-icons-in-nativescript-angular-apps/ for more details.

**Comment by robophil** [comment]
```css

$mdi-600: 600;
.mdi {
    font-family: "Material Icons", "MaterialIcons-Regular";
}

.mdi-600 {
    @extend .mdi;
    font-size: $mdi-600;
}

```

The link was what i used in setting this up. Some icons show, but others don't eg `mid-hourglass_empty` among others, and it exists in the css file. so its a bit surprising. I thought about updating the `.ttf` file
